import curses

#UP = [curses.KEY_UP, ord('k'), ord('w')]
#DOWN = [curses.KEY_DOWN, ord('j'), ord('s')]
#LEFT = [curses.KEY_LEFT, ord('h'), ord('a')]
#RIGHT = [curses.KEY_RIGHT, ord('l'), ord('d')]
UP = [curses.KEY_UP, ord('w')]
DOWN = [curses.KEY_DOWN, ord('s')]
LEFT = [curses.KEY_LEFT, ord('a')]
RIGHT = [curses.KEY_RIGHT, ord('d')]
SELECT = [curses.KEY_ENTER, 10, ord(' ')]
BACK = [curses.KEY_BACKSPACE, 127, -1]
DEBUG_H = [ord('h')]
DEBUG_J = [ord('j')]
DEBUG_K = [ord('k')]
DEBUG_L = [ord('l')]
EXIT = []
MENUKEY = [ord('m'), ord('M')]
DEBUGKEY = [ord('`')]
