TARGET_NONE = -1
SELF = 0 # User
ENEMY = 1 # Any enemy
ACTIVE = 2 # currently active enemy
MULTI_SELF = 3 # All friendly
MULTI_ENEMY = 4 # all enemies

ARMOR_HEAD = 100
ARMOR_BODY = 101
ARMOR_LEGS = 102
ARMOR_SHIELD = 103

WEAPON_ONEHAND = 110
WEAPON_TWOHAND = 111

